--- # splunk on a aws server

- hosts: splunk
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Download Splunk
      get_url: url=https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.3&product=splunk&filename=splunk-7.0.3-fa31da744b51-Linux-x86_64.tgz&wget=true force=yes
    - name: Move the splunk tar
      command: mv splunk-7.0.3-fa31da744b51-Linux-x86_64.tgz /opt
   -  name: Extract Splunk Binary
      command: chdir=/opt tar -xzvf splunk-7.0.3-fa31da744b51-Linux-x86_64.tgz 
    - name: Start splunk
      command: /opt/splunk/bin/splunk start --accept-license
